{
 "title": "Frontend",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "label_values(app)" }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TTFB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(ttfb_sum[$__interval])"
    }
   ]
  },
  {
   "title": "FCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(fcp_sum[$__interval])"
    }
   ]
  },
  {
   "title": "CLS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(cls_sum[$__interval])"
    }
   ]
  },
  {
   "title": "LCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(lcp_sum[$__interval])"
    }
   ]
  },
  {
   "title": "FID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(fid_sum[$__interval])"
    }
   ]
  },
  {
   "title": "Page Load, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, ttfb_sum[5m])",
     "legendFormat": "TTFB"
    },
    {
     "expr": "quantile_over_time(0.75, lcp_sum[5m])"
    },
    {
     "expr": "quantile_over_time(0.75, fcp_sum{name=\"FCP\"}[5m])"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, cls_sum{name=\"CLS\"}[$__interval])"
    }
   ]
  },
  {
   "title": "First Input Delay, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, fid_sum{name=\"FID\"}[$__interval])",
     "legendFormat": "FID"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$app\",kind=\"exception\"} [$__range])) by (app)",
     "operation": "windowsExceptionTrap",
     "service": "shell-🐒"
    }
   ]
  },
  {
   "title": "Exceptions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time({app=\"$app\",kind=\"exception\"} [$__interval])",
     "legendFormat": "errors",
     "operation": "windowsExceptionTrap",
     "service": "shell-🐒"
    }
   ]
  },
  {
   "title": "Top Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 13 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({kind=\"exception\", app=\"$app\"} | logfmt [$__range])) by (value))",
     "operation": "windowsExceptionTrap",
     "service": "shell-🐒"
    }
   ]
  },
  {
   "title": "Top URLs by Exception Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({kind=\"exception\", app=\"$app\"} | logfmt [$__range])) by (page_url))",
     "operation": "windowsExceptionTrap",
     "service": "shell-🐒"
    }
   ]
  },
  {
   "title": "Top Browsers by Exception Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 14, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, count by (browser_name, browser_version) (count_over_time({kind=\"exception\", app=\"$app\"} | logfmt [$__range])))"
    }
   ]
  },
  { "title": "Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Popular Browsers",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({app=\"$app\",kind=\"measurement\"} |= \" ttfb=\" | logfmt [$__range])) by (browser_name, browser_version))",
     "service": "shell-🐒"
    }
   ]
  },
  {
   "title": "Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 31 },
   "targets": [
    {
     "expr": "count_over_time({app=\"$app\",kind=\"measurement\"} |= \" ttfb=\" [$__interval])",
     "legendFormat": "visits"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Top Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({kind=\"event\", app=\"$app\"} | logfmt [$__range])) by (event_name))"
    }
   ]
  }
 ]
}