apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-ctrl-app
  labels:
    app: rust-ctrl-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-ctrl-app
  template:
    metadata:
      labels:
        app: rust-ctrl-app
    spec:
      serviceAccountName: rust-ctrl-sa
      containers:
        - name: rust-ctrl
          image: localhost:5000/rust-ctrl:latest
          # image: host.docker.internal:5000/rust-ctrl:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "2" # Set CPU limit to 2 cores
          env:
            - name: RUST_LOG
              value: "info,tokio=debug"
            - name: CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
                  divisor: "1" # Get CPU limit as a float
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
